### ISSUE TITLE
Displays directory listing

### ISSUE THREAD

**Issue by baisong** [NathanielHill/now-static-redirect#1]
I know I'm probably just missing something...

1. Clone repo
2. Replace alias and destination values
3. `now && now alias`
4. When I view the alias in my browser I see:

![screenshot from 2019-01-11 18-46-44](https://user-images.githubusercontent.com/228733/51068329-5b8fa700-15d1-11e9-9ba8-d605e8dc315e.png)

**Comment by NathanielHill** [comment]
I'm not surprised, Zeit has deprecated the `package.json` field in favor of `now.json` for a while. This repo was an experiment on Now V1, and I would not recommend using it at this point.

At this time I would recommend the technique in https://github.com/NathanielHill/zeit-redirect-demo

You can see the same technique is used in the official example repo: https://github.com/zeit/now-examples/tree/master/redirect

**Comment by baisong** [comment]
Thank you @NathanielHill!
